apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-storage
provisioner: dobs.csi.digitalocean.com
parameters:
  type: ssd
  fsType: ext4
  iopsPerGB: "200"
reclaimPolicy: Retain
volumeBindingMode: Immediate