apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-app
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Host "209.38.113.90"; # Ensures the original Host header is passed to the backend
      proxy_set_header X-Forwarded-Host "209.38.113.90"; # Forwarding the host header for better routing visibility
      location /media/ {
        proxy_pass http://khedma123456789.ddns.net;
        proxy_set_header Host "209.38.113.90";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host "209.38.113.90";
      }

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - khedma123456789.ddns.net
    secretName: example-app-tls
  rules:
  - host: khedma123456789.ddns.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: example-service
            port:
              number: 80
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: khedma  
            port:
              number: 80
      # - path: /media/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       exteramename: example-service  # Same backend service or another for static content
      #       port:
      #         number: 80

