apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      securityContext:
        fsGroup: 1000
      hostname: backend-service
      # affinity:
      #   podAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       - labelSelector:
      #           matchLabels:
      #             app: backend-app
      #         topologyKey: "kubernetes.io/hostname"
      containers:
        - name: backend-app
          image: mohamedamineblibech/backend:v1.150
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: kh-secret
            - configMapRef:
                name: django-config
          volumeMounts:
            - name: media-volume-mount
              mountPath: /django/khedma/media
      volumes:
        - name: media-volume-mount
          persistentVolumeClaim:
            claimName: media-pvc-local
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
  labels:
    app: backend-app
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080  # The port your backend is listening on (on the external server)
      targetPort: 80
