apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: default
  labels:
    type: block-storage
spec:
  storageClassName: do-media-storage  # New StorageClass for media
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi