apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: media-storage
provisioner: dobs.csi.digitalocean.com
parameters:
  type: hdd
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: Immediate