apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-phases
  namespace: argocd # The namespace where ArgoCD is running
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: argocd_wetekup
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd_wetekup
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd_wetekup
spec:
  destination:
    namespace: default # The namespace where the application will be deployed
    server: "https://kubernetes.default.svc" # Default Kubernetes API endpoint
  project: default
  source:
    path: k8s # Directory where your manifests are stored in the repo
    repoURL: "https://github.com/med363/argocd-khedmasite.git" # Repository URL
    targetRevision: HEAD # Branch, tag, or commit to deploy
  syncPolicy:
    automated:
      prune: true # Automatically delete old resources
      selfHeal: true # Correct drifted resources automatically
    syncOptions:
      - CreateNamespace=true # Create namespace if it doesn't exist
