apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-phases
  namespace: argocd # The namespace where ArgoCD is running
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: argocd_wetekup
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd_wetekup
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd_wetekup
spec:
  destination:
    namespace: default # The namespace where the application will be deployed
    server: "https://kubernetes.default.svc" # Ensure this is correct for your cluster, usually this is fine in most setups
  project: default
  source:
    path: k8s # Directory where your manifests are stored in the repo
    repoURL: "https://github.com/med363/argocd-khedmasite.git" # Make sure this is the correct repository URL
    targetRevision: HEAD # Can be a specific branch, tag, or commit
    directory:
      recurse: true # Ensures all resources within the directory are included
  syncPolicy:
    automated:
      prune: true # Ensures deletion of resources that have been removed or renamed from the repo
    syncOptions:
      - CreateNamespace=true # Automatically creates namespaces if they don't exist
